### ISSUE TITLE
Unauthorised redistribution of NootedRed

### ISSUE THREAD

**Issue by ChefKissInc** [laobamac/NootedRed-Release#1]
@laobamac Binaries are our intellectual property too. As per copyright law, we demand deletion of this repository. Refusal of our wishes is illegal and we will take legal action. You have a grace period of 2 days.

**Comment by ChefKissInc** [comment]
@laobamac Reminder

**Comment by laobamac** [comment]
I am aware, thank you for your reminder. I apologize to the NootedRed author team.
